initial deploy trial

diff --git a/deploy/docker/Jenkinsfile b/deploy/docker/Jenkinsfile
--- a/deploy/docker/Jenkinsfile
+++ b/deploy/docker/Jenkinsfile
@@ -25,8 +25,8 @@ pipeline {
                     env.TF_VAR_aws_security_group = accountConfig.security_group
                     env.TF_VAR_aws_subnet_ids = accountConfig.subnet_ids
                     env.TF_VAR_aws_vpc_id = accountConfig.vpc_id
-                    env.aws_tf_bucket = accountConfig.tf_bucket
-                    env.aws_tf_table = accountConfig.tf_table
+                    env.TF_BUCKET = accountConfig.tf_bucket
+                    env.TF_TABLE = accountConfig.tf_table
                     env.TF_VAR_aws_ssl_certificate_arn = accountConfig.ssl_certificate_arn
                     env.TF_VAR_aws_route53_zone_id = accountConfig.route53_zone_id
                     env.TF_VAR_aws_domain = accountConfig.domain
@@ -41,8 +41,8 @@ pipeline {
                     echo "Security Group: ${env.TF_VAR_aws_security_group}"
                     echo "Subnet IDs: ${env.TF_VAR_aws_subnet_ids}"
                     echo "VPC ID: ${env.TF_VAR_aws_vpc_id}"
-                    echo "Terraform Bucket: ${env.aws_tf_bucket}"
-                    echo "Terraform Table: ${env.aws_tf_table}"
+                    echo "Terraform Bucket: ${env.TF_BUCKET}"
+                    echo "Terraform Table: ${env.TF_TABLE}"
                     echo "SSL Certificate ARN: ${env.TF_VAR_aws_ssl_certificate_arn}"
                     echo "Route53 Zone ID: ${env.TF_VAR_aws_route53_zone_id}"
                     echo "Domain: ${env.TF_VAR_aws_domain}"
@@ -50,50 +50,109 @@ pipeline {
                 }
             }
         }
-        // stage('AssumeRole') {
-        //     steps {
-        //         script {
-        //             def assumeRoleCmd = """
-        //                 aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ROLE_NAME} --role-session-name CrossAccountSession
-        //             """
-        //             def assumeRoleOutput = sh(script: assumeRoleCmd, returnStdout: true).trim()
-        //             def creds = readJSON(text: assumeRoleOutput).Credentials
+        stage('Terraform Backend') {
+            steps {
+                script {
+                        terraformInit = {
+                            sh """
+                                terraform init -reconfigure \
+                                    -backend-config="bucket=${env.TF_BUCKET}" \
+                                    -backend-config="key=${env.TF_VAR_aws_domain}/terraform.tfstate" \
+                                    -backend-config="region=${AWS_REGION}" \
+                                    -backend-config="dynamodb_table=${env.TF_TABLE}"
+                            """
+                        }
+                }
+            }
+        }
+        stage('AssumeRole') {
+            steps {
+                script {
+                    def assumeRoleCmd = """
+                        aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ROLE_NAME} --role-session-name CrossAccountSession
+                    """
+                    def assumeRoleOutput = sh(script: assumeRoleCmd, returnStdout: true).trim()
+                    def creds = readJSON(text: assumeRoleOutput).Credentials
 
-        //             env.AWS_ACCESS_KEY_ID = creds.AccessKeyId
-        //             env.AWS_SECRET_ACCESS_KEY = creds.SecretAccessKey
-        //             env.AWS_SESSION_TOKEN = creds.SessionToken
-        //         }
-        //     }
-        // }
-        // stage('TerraformInit') {
-        //     steps {
-        //         script {
-        //                 terraformInit = {
-        //                     sh """
-        //                         terraform init -reconfigure \
-        //                             -backend-config="bucket=${env.TF_VAR_aws_tf_bucket}" \
-        //                             -backend-config="key=${env.TF_VAR_aws_domain}/terraform.tfstate" \
-        //                             -backend-config="region=${AWS_REGION}" \
-        //                             -backend-config="dynamodb_table=terraform-lock-table"
-        //                     """
-        //                 }
-        //         }
-        //     }
-        // }
-        // stage('Build Docker Image') {
-        //     steps {
-        //         script {
-        //             sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
-        //         }
-        //     }
-        // }
-        // stage('Publish Docker Image') {
-        //     steps {
-        //         script {
-        //             sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
-        //             sh 'docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
-        //         }
-        //     }
-        // }
+                    env.AWS_ACCESS_KEY_ID = creds.AccessKeyId
+                    env.AWS_SECRET_ACCESS_KEY = creds.SecretAccessKey
+                    env.AWS_SESSION_TOKEN = creds.SessionToken
+                }
+            }
+        }
+        stage('Terraform Destroy Infrastructure') {
+            when {
+                expression { params.Options == 'Deploy' || params.Options == 'Destroy' }
+            }
+            steps {
+                // go to deploy/docker directory
+                dir('deploy/docker') {
+                    terraformInit()
+                    sh 'terraform destroy -auto-approve || echo "No existing infrastructure to destroy."'
+                }
+            }
+        }
+        stage('Terraform Deploy ECR Repository') {
+            when {
+                expression { params.Options == 'Deploy'  }
+            }
+            steps {
+                script {
+                    dir('deploy/docker') {
+                        terraformInit()
+                        try {
+                            sh 'terraform plan -out=ecr.tfplan -target=aws_ecr_repository.ecr'
+                        } catch (Exception e) {
+                            echo "Terraform plan failed: ${e}"
+                            echo "Exiting due to Terraform plan failure"
+                        }
+                        try {
+                            sh 'terraform apply -auto-approve ecr.tfplan'
+                            env.ECR_REPOSITORY_URL = sh(script: 'terraform output -raw ecr_repository_url', returnStdout: true).trim()
+                            sh 'echo "ECR Repository URL: ${ECR_REPOSITORY_URL}"'
+                        } catch (Exception e) {
+                            echo "Terraform apply failed: ${e}"
+                            echo "Rolling back changes"
+                            sh "terraform destroy -auto-approve"
+                            echo "Exiting due to Terraform apply failure"
+                        }
+                    }
+                }
+            }
+        }
+        stage('Build Docker Image') {
+            when {
+                expression { params.Options == 'Deploy' || params.Options == 'Update'  }
+            }
+            steps {
+                script {
+                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
+                }
+            }
+        }
+        stage('Publish Docker Image') {
+            when {
+                expression { params.Options == 'Deploy' || params.Options == 'Update'  }
+            }
+            steps {
+                script {
+                    sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
+                    sh 'docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
+                }
+            }
+        }
+        stage('Terraform Update ECS Service') {
+            when {
+                expression { params.Options == 'Deploy' || params.Options == 'Update'  }
+            }
+            steps {
+                script {
+                    dir('deploy/docker') {
+                        terraformInit()
+                        sh "terraform apply -auto-approve -var 'ecr_image=${ECR_REPOSITORY_URL}:${IMAGE_TAG}'"
+                    }
+                }
+            }
+        }
     }
 }
